--- # This is a sample file. Please customize it before using.
PeerID: 102
PeerHost: localhost
IndexServerPort: 5700
FileServerPort: 5711

Neighbors:
  - PeerID: 102
    PeerHost: 64.131.105.115
    IndexServerPort: 5700
    FileServerPort: 5711
